### PR TITLE
Add Greeting Component

### PR DESCRIPTION
**Pull request by Bateyjosue**
### TASK
Render a react component using redux store to return a random greeting stored in PostgreSQL database from the rails endpoint fetched using axios

## Happy Review

### CODE REVIEW

**Comment by addod19** [comment]
### Hi @Bateyjosue, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that is invalid because we did not follow the Git-flow work flow. That is, creating a PR from `react_rails` branch into the `dev` branch. What we have currently is Github work flow. Let us kindly fix it

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by mckent05 — COMMENTED** [review]
Hi @Bateyjosue, 

# STATUS: INVALID REQUEST ❌ ❌ 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that does not follow the required workflow, please note that you are required to use Gitflow for this milestone, Therefore your PR should merge from a `feature` branch into the `dev` branch. Please fix this 🙏 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by Bateyjosue** [comment]
what's wrong with you Man. It should be consider as well as a external the way we are doing it in group project
is this the real why is invalid.

**Review by franclobo — CHANGES_REQUESTED** [review]
Hi @Bateyjosue, 

# ♻️ Required Changes ♻️

so-close-jim-halpert

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights

- No linter errors ✔️ 
- Descriptive PR ✔️ 
- Gem jsbundling-rails is used 💯 


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- [ ] Please 🙏🏽 make sure that you have followed the [instructions](https://betterprogramming.pub/react-with-rails-2022-bd28e1fcd355#ad0a) step by step and using yarn instead of npm. When I tried to run your app the terminal returned this message 👇🏽 

image


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Bateyjosue** [comment]
Hey @franclobo, it is installed on my local machine, of course, may in yours
can you try to use ruby version 3.1.2 because once I push the code that versions it brings a linter if possible you can try it please and then see the output it can help because even I try to add I can not accept to be a push. and if I installed it on my local machine you want to be able to use see.

**Comment by franclobo** [comment]
> Hey @franclobo, it is installed on my local machine, of course, may in yours can you try to use ruby version 3.1.2 because once I push the code that versions it brings a linter if possible you can try it please and then see the output it can help because even I try to add I can not accept to be a push. and if I installed it on my local machine you want to be able to use see.

Hi, @Bateyjosue. May you did any changes to the dev file or Procfile.dev or installed another gem?

**Comment by Bateyjosue** [comment]
See @franclobo  the problem is not that i have developed the app using ruby 3.1.2 but once i pushed it bring linters that why i had to change to 2.7.6 to fix the linter means you could have check the code using any version

**Review by emmanuellekamwa — APPROVED** [review]
**STATUS: APPROVED 🍾✔🎉**
Hello @Bateyjosue 👋
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights

- You documented your work professionally.✔
- You asked for the changes in a polite and friendly way.
- Your linters are passing all the checks.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
